### ISSUE TITLE
Lint YAML and Python files on CI

### ISSUE THREAD

**Issue by MattiSG** [openfisca/country-template#114]
OpenFisca-France has tests to automatically lint [YAML](https://github.com/openfisca/openfisca-france/blob/master/.circleci/lint-changed-yaml-tests.sh) and [Python](https://github.com/openfisca/openfisca-france/blob/master/.circleci/lint-changed-python-files.sh) files.

I believe the publishing process is already part of the OpenFisca Country Template suggestions, and that maintaining consistent quality and syntax is a meaningful way to ease contribution.

I thus suggest importing these tests, alongside any other improvements made to the testing procedure, to the Country Template (probably toning down a bit the tongue-in-cheek phrasings 😉).

Opinions welcome @openfisca/international-contrib!

**Comment by HAEKADI** [comment]
@MattiSG Should we only add the linting job, or restructure the entire CircleCI configuration like we did with `OpenFisca France` [here](https://github.com/openfisca/openfisca-france/pull/1650)?

The restructuring would include amongst other things:

*  Separating the `install` from the `build`
*  Separating the `build`and the `test`
*  Using `openfisca test` instead of `make test`, which does check for syntax errors and does some linting as well
*  Adding a separate job which lints Python and YAML files
*  Changing the job dependencies in the workflow

**Comment by MattiSG** [comment]
Yes, and we should also switch to GitHub Actions as agreed on https://github.com/openfisca/openfisca-core/issues/1030 😉
This issue is only about adding linting. It can be closed alongside others if a larger PR is open on that topic 🙂
